name: Integration Tests

on:
  push:
    branches:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Dependencies
        uses: actions/setup-python@v4
      - name: Install trec-auto-judge from the repo
        working-directory: ${{github.workspace}}
        run: |
          pip3 install .[test]
          pip3 install --no-deps ir_datasets
          pip3 uninstall -y tira
          pip3 install tira

      - name: Download Cache From TIRA
        run: |
          wget 'https://www.tira.io/task/trec-auto-judge/user/webis/dataset/kiddie-20260605-training/download/2026-07-10-08-52-33.zip'
          unzip -j 2026-07-10-08-52-33.zip '2026-07-10-08-52-33/CACHE_DIR/*' -d example-cache-kiddie
      - name: Test judges/queryonly
        run: |
          export OPENAI_API_KEY=ignore
          export OPENAI_BASE_URL=ignore
          export OPENAI_MODEL=llama-3.1-8b-instant

          tira-cli code-submission \
              --dry-run \
              --path . \
              --cache-behaviour deterministic \
              --mount-cache '$CACHE_DIR=example-cache-kiddie' \
              --forward-environment-variable OPENAI_API_KEY OPENAI_BASE_URL OPENAI_MODEL \
              --task trec-auto-judge \
              --dataset kiddie-20260605-training \
              --command 'auto-judge run --workflow /auto-judge/judges/queryonly/workflow.yml --rag-responses $inputDataset/runs/*/ --rag-topics $inputDataset/topics/*.jsonl --out-dir $outputDir'

